version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: book_exchange_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bookex
    ports:
      - "${MONGODB_EXPOSE}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - book_exchange_network

  bot:
    build: .
    container_name: book_exchange_bot
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - mongodb
    networks:
      - book_exchange_network

volumes:
  mongodb_data:
    name: book_exchange_mongodb_data

networks:
  book_exchange_network:
    name: book_exchange_network
    driver: bridge