version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: book_exchange_mongodb
    restart: unless-stopped
    command: mongod --port ${MONGODB_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}
    ports:
      - "127.0.0.1:${MONGODB_EXPOSE}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db

  bot:
    build: .
    container_name: book_exchange_bot
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src

volumes:
  mongodb_data:
    name: book_exchange_mongodb_data